### Create admin or staff
POST http://localhost:8000/api/admin/register
Content-Type: application/json

{
    "username": "Admin",
    "email": "admin@example.com",
    "password": "admin"
}

### Login admin
POST http://localhost:8000/api/admin/login 
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin"
}

### Admin list
GET http://localhost:8000/api/admin/list 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NGY5Nzg3YWIwMzAwNjEwNzU2ZDQwYjYiLCJyb2xlIjoiR0VORVJBTCIsIm5hbWUiOiJBZG1pbiIsImlhdCI6MTY5NDA3MTYyMiwiZXhwIjoxNjk0MDc1MjIyfQ.vePWSD5BA0lBvDA5Wvo_x_F-M7GqJBAyEHvz9Gcn94s